# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
  admin_email: "yueyuan0416@gmail.com"
  system_email: "yueyuan0416@gmail.com"
  webpush:
    public_key: "BCLZu6pNdkx4A7rQ3NBWbc-ULpysqcJOUD-BZEaGYRPzBf90BNK3_7AgLN3OlYE9K3ZSu_rqAMnF3raZslw-Lv0"
    private_key: "m63jP4o0feZPlc0Rk8BQvoaPe5AxQFhDWgp_YykheJU"
    subject: "mailto:yueyuan0416@gmail.com"

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"

  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones

  App\EventListener\LocaleListener:
    tags:
      - { name: kernel.event_listener, event: kernel.request, priority: 15 }

  App\Service\OrderMailer:
    arguments:
      $adminEmail: "%env(ADMIN_EMAIL)%"
      $systemEmail: "%env(SYSTEM_EMAIL)%"

  App\Service\PushNotificationService:
    arguments:
      $vapidPublicKey: "%webpush.public_key%"
      $vapidPrivateKey: "%webpush.private_key%"
      $vapidSubject: "%webpush.subject%"

  App\Service\OrderService:
    arguments:
      $entityManager: "@doctrine.orm.entity_manager"
      $mailer: "@mailer.mailer"
      $twig: "@twig"
      $requestStack: "@request_stack"
      $translator: "@translator"
      $logger: "@logger"
      $adminEmail: "%env(ADMIN_EMAIL)%"
